Return-Path: barracuda@zimbratest.example.com
Received: from zimbra86-test.example.com (LHLO zimbra86-test.example.com)
 (10.0.3.64) by zimbra86-test.example.com with LMTP; Thu, 31 Dec 2015
 17:25:54 +0100 (CET)
Received: from localhost (localhost [127.0.0.1])
    by zimbra86-test.example.com (Postfix) with ESMTP id 9EA54FA2BD6
    for <albacore@zimbratest.example.com>; Thu, 31 Dec 2015 17:25:54 +0100 (CET)
X-Spam-Flag: NO
X-Spam-Score: -0.109
X-Spam-Level:
X-Spam-Status: No, score=-0.109 tagged_above=-10 required=6.6
    tests=[ALL_TRUSTED=-1, BAYES_20=-0.001, DKIM_ADSP_NXDOMAIN=0.9,
    HTML_MESSAGE=0.001, NO_DNS_FOR_FROM=0.001, T_RP_MATCHES_RCVD=-0.01]
    autolearn=no autolearn_force=no
Received: from zimbra86-test.example.com ([127.0.0.1])
    by localhost (zimbra86-test.example.com [127.0.0.1]) (amavisd-new, port 10032)
    with ESMTP id 9ImOryaQ3UcM for <albacore@zimbratest.example.com>;
    Thu, 31 Dec 2015 17:25:54 +0100 (CET)
Received: from localhost (localhost [127.0.0.1])
    by zimbra86-test.example.com (Postfix) with ESMTP id 0265FFA2BD7
    for <albacore@zimbratest.example.com>; Thu, 31 Dec 2015 17:25:54 +0100 (CET)
X-Virus-Scanned: amavisd-new at zimbra86-test.example.com
Received: from zimbra86-test.example.com ([127.0.0.1])
    by localhost (zimbra86-test.example.com [127.0.0.1]) (amavisd-new, port 10026)
    with ESMTP id daxUSzastAPc for <albacore@zimbratest.example.com>;
    Thu, 31 Dec 2015 17:25:53 +0100 (CET)
Received: from zimbra86-test.example.com (zimbra86-test.example.com [10.0.3.64])
    by zimbra86-test.example.com (Postfix) with ESMTP id 7EEC9FA2BD6
    for <albacore@zimbratest.example.com>; Thu, 31 Dec 2015 17:25:53 +0100 (CET)
Date: Thu, 31 Dec 2015 17:25:53 +0100 (CET)
From: barracuda@zimbratest.example.com
To: albacore <albacore@zimbratest.example.com>
Message-ID: <334055399.283.1451579153094.JavaMail.zimbra@zimbratest.example.com>
Subject: =?utf-8?Q?Joyeux_No=C3=ABl_!?=
MIME-Version: 1.0
Content-Type: multipart/alternative; 
    boundary="----=_Part_282_1095497014.1451579153094"
X-Originating-IP: [10.0.3.1]
X-Mailer: Zimbra 8.6.0_GA_1191 (ZimbraWebClient - FF43 (Linux)/8.6.0_GA_1191)
Thread-Topic: Joyeux =?utf-8?B?Tm/Dq2w=?= !
Thread-Index: b6u9KR6Fe954QNawlYCDcklwLCbMUQ==

------=_Part_282_1095497014.1451579153094
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: quoted-printable

Hi there !=20

Bien cordialement,=20
Barracuda=20
Administrateur syst=C3=A8mes=20
OASISWORK=20

------=_Part_282_1095497014.1451579153094
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: quoted-printable

<html><body><div style=3D"font-family: arial, helvetica, sans-serif; font-s=
ize: 12pt; color: #000000"><div>Hi there !<br></div><div><br></div><div dat=
a-marker=3D"__SIG_PRE__"><div><span style=3D"font-size: small;"><span style=
=3D"color: #009900;"><span><span style=3D"font-family: verdana,helvetica,sa=
ns-serif; color: #333333; font-size: small;"><span style=3D"font-size: smal=
l;"><span style=3D"color: #009900;"><span style=3D"color: #000000;">Bien co=
rdialement,</span><br></span></span></span></span></span></span></div><div>
</div><div><span style=3D"font-size: small;"><span style=3D"color: #009900;=
"><span><span style=3D"font-family: verdana,helvetica,sans-serif; color: #3=
33333; font-size: small;"><span style=3D"font-size: small;"><span style=3D"=
color: #009900;"><span style=3D"color: #000000;">&nbsp;</span></span></span=
></span></span></span></span></div><div>
</div><div><span style=3D"font-size: small;"><span style=3D"color: #009900;=
"><span><span style=3D"font-family: verdana,helvetica,sans-serif; color: #3=
33333; font-size: small;"><span style=3D"font-size: small;"><span style=3D"=
color: #009900;">Barracuda</span></span><br></span></span><span><span style=
=3D"font-family: verdana,helvetica,sans-serif; color: #333333; font-size: s=
mall;"><span style=3D"font-size: xx-small;"><span style=3D"color: #666666;"=
>Administrateur syst=C3=A8mes</span></span></span></span><br><span><span st=
yle=3D"font-family: verdana,helvetica,sans-serif; color: #333333; font-size=
: small;"><span style=3D"font-size: small;"><span style=3D"color: #009900;"=
>OASISWORK</span></span></span></span></span></span></div><div></div></div>=
</div></body></html>
------=_Part_282_1095497014.1451579153094--
